services:
  - type: web
    name: fifa26-api
    runtime: node
    plan: free
    rootDir: apps/api
    buildCommand: pnpm install --frozen-lockfile=false --prod=false && pnpm build
    startCommand: pnpm start:prod
    envVars:
      - key: PORT
        value: 10000

      - key: DATABASE_URL
        sync: false

      - key: FRONTEND_URL
        sync: false

      - key: NEWS_API_URL
        value: "https://api.currentsapi.services/v1/"

      - key: NEWS_API_TOKEN
        sync: false

      - key: SPORTSMONK_API_URL
        value: "https://api.sportmonks.com/v3/football/"

      - key: SPORTSMONK_API_TOKEN
        sync: false

      - key: THESPORTSDB_API_URL
        value: "https://www.thesportsdb.com/api/v1/json/123/"
