export type Player = {
  id: string;
  name: string;
  position: string;
  shirtNumber?: number;
  idPlayer?: string;
  idTeam?: string;
  idTeam2?: string | null;
  idTeamNational?: string | null;
  idAPIfootball?: string | null;
  idPlayerManager?: string | null;
  idWikidata?: string | null;
  idTransferMkt?: string | null;
  idESPN?: string | null;
  strNationality?: string | null;
  strPlayer?: string | null;
  strPlayerAlternate?: string | null;
  strTeam?: string | null;
  strTeam2?: string | null;
  strSport?: string | null;
  intSoccerXMLTeamID?: string | null;
  dateBorn?: string | null;
  dateDied?: string | null;
  strNumber?: string | null;
  dateSigned?: string | null;
  strSigning?: string | null;
  strWage?: string | null;
  strOutfitter?: string | null;
  strKit?: string | null;
  strAgent?: string | null;
  strBirthLocation?: string | null;
  strDeathLocation?: string | null;
  strEthnicity?: string | null;
  strStatus?: string | null;
  strDescriptionEN?: string | null;
  strDescriptionDE?: string | null;
  strDescriptionFR?: string | null;
  strDescriptionCN?: string | null;
  strDescriptionIT?: string | null;
  strDescriptionJP?: string | null;
  strDescriptionRU?: string | null;
  strDescriptionES?: string | null;
  strDescriptionPT?: string | null;
  strDescriptionSE?: string | null;
  strDescriptionNL?: string | null;
  strDescriptionHU?: string | null;
  strDescriptionNO?: string | null;
  strDescriptionIL?: string | null;
  strDescriptionPL?: string | null;
  strGender?: string | null;
  strSide?: string | null;
  strPosition?: string | null;
  strCollege?: string | null;
  strFacebook?: string | null;
  strWebsite?: string | null;
  strTwitter?: string | null;
  strInstagram?: string | null;
  strYoutube?: string | null;
  strHeight?: string | null;
  strWeight?: string | null;
  intLoved?: string | null;
  strThumb?: string | null;
  strPoster?: string | null;
  strCutout?: string | null;
  strCartoon?: string | null;
  strRender?: string | null;
  strBanner?: string | null;
  strFanart1?: string | null;
  strFanart2?: string | null;
  strFanart3?: string | null;
  strFanart4?: string | null;
  strCreativeCommons?: string | null;
  strLocked?: string | null;
  strLastName?: string | null;
};

export type TeamStats = {
  played: number;
  won: number;
  drawn: number;
  lost: number;
  goalsFor: number;
  goalsAgainst: number;
};

export type Team = {
  id: string;
  name: string;
  country: string;
  name_normalised?: string;
  continent?: string;
  flag_icon?: string;
  flag_unicode?: string;
  fifa_code?: string;
  confed?: string;
  image_url?: string | null;
  sportsdb_team_id?: string | null;
  logoUrl?: string;
  flagUrl?: string;
  shortCode?: string;
  group?: string;
  coach?: string;
  fifaRanking?: number;
  stats?: TeamStats;
  players?: Player[];
  idAPIfootball?: string | null;
  idESPN?: string | null;
  idLeague?: string | null;
  idLeague2?: string | null;
  idLeague3?: string | null;
  idLeague4?: string | null;
  idLeague5?: string | null;
  idLeague6?: string | null;
  idLeague7?: string | null;
  idTeam?: string | null;
  idVenue?: string | null;
  intFormedYear?: string | null;
  intLoved?: string | null;
  intStadiumCapacity?: string | null;
  strBadge?: string | null;
  strBanner?: string | null;
  strColour1?: string | null;
  strColour2?: string | null;
  strColour3?: string | null;
  strCountry?: string | null;
  strDescriptionCN?: string | null;
  strDescriptionDE?: string | null;
  strDescriptionEN?: string | null;
  strDescriptionES?: string | null;
  strDescriptionFR?: string | null;
  strDescriptionHU?: string | null;
  strDescriptionIL?: string | null;
  strDescriptionIT?: string | null;
  strDescriptionJP?: string | null;
  strDescriptionNL?: string | null;
  strDescriptionNO?: string | null;
  strDescriptionPL?: string | null;
  strDescriptionPT?: string | null;
  strDescriptionRU?: string | null;
  strDescriptionSE?: string | null;
  strDivision?: string | null;
  strEquipment?: string | null;
  strFacebook?: string | null;
  strFanart1?: string | null;
  strFanart2?: string | null;
  strFanart3?: string | null;
  strFanart4?: string | null;
  strGender?: string | null;
  strInstagram?: string | null;
  strKeywords?: string | null;
  strLeague?: string | null;
  strLeague2?: string | null;
  strLeague3?: string | null;
  strLeague4?: string | null;
  strLeague5?: string | null;
  strLeague6?: string | null;
  strLeague7?: string | null;
  strLocation?: string | null;
  strLocked?: string | null;
  strLogo?: string | null;
  strRSS?: string | null;
  strSport?: string | null;
  strStadium?: string | null;
  strTeam?: string | null;
  strTeamAlternate?: string | null;
  strTeamShort?: string | null;
  strTwitter?: string | null;
  strWebsite?: string | null;
  strYoutube?: string | null;
};
